name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
 
      uses: docker/login-action@v2.0.0
      with:
        username: fizetesipont
        password: ${{secrets.dockerpw}}
 
    - name: Build the Docker image
      run: 
          docker build ./samplewebapp --file samplewebapp/Dockerfile --tag SzekelyLegio/samplewebapp:latest
          docker push SzekelyLegio/samplewebapp:latest
